alter session set "_ORACLE_SCRIPT"=true;
create user dbadmin identified by dbadmin
        default tablespace users
        TEMPORARY TABLESPACE temp
        Quota 10M on users;
/
--Grant quyen cho dbadmin
grant dba to dbadmin;
GRANT ALL PRIVILEGES, CREATE SESSION, CREATE USER, ALTER USER, DROP USER, CREATE ROLE, ALTER ANY ROLE, DROP ANY ROLE, CREATE PROCEDURE, EXECUTE ANY PROCEDURE, ALTER ANY PROCEDURE, DROP ANY PROCEDURE, SELECT ANY TABLE, CREATE TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, DROP ANY TABLE TO DBADMIN WITH ADMIN OPTION;
